version: 0.1.0.{build}
branches:
  only:
    - master
platform: x64
environment:
  nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y
  - set Path=%Path%;C:\Users\appveyor\.cargo\bin
  - rustup toolchain install nightly
  - cinst yarn
build_script:
  - ps: cd ui; yarn install
  - ps: cd ui; yarn run build
  - cargo build --verbose --all
test_script:
  - cargo test --verbose --all
  - ps: cd ui && yarn run unit
